theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = true
end-of-line-diagnostics = "hint"

[editor.lsp]
display-inlay-hints = false


[editor.inline-diagnostics]
cursor-line = "warning" 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
K = "hover"
"F8" = ":toggle lsp.display-inlay-hints"
"F1" = ":config-reload"
"F2" = ":theme modus_operandi"
X = ["select_line_above", "extend_to_line_bounds"]
V = "extend_to_line_bounds"
A-x = "extend_to_line_bounds"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal.space]
k = "keep_selections"
g = { d = [":vsplit", "goto_definition"]}

[keys.normal.space.s]
f = "file_picker"
n = ":open ~/.config/helix/"

[keys.insert]  
"C-y" = "insert_tab" 

[keys.select]
X = ["select_line_above", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
