theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
mouse = true

[editor.lsp]
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
K = "hover"
"F8" = ":toggle lsp.display-inlay-hints"
"F1" = ":config-reload"

[keys.normal.space]
k = "keep_selections"

[keys.normal.space.s]
f = "file_picker"

