
# -------------------------------
# Language Servers Configuration
# -------------------------------

[language-server]
elixir-ls = { command = "elixir-ls", config = { elixirLS.dialyzerEnabled = false } }

[language-server.tinymist]
config = { formatterMode = "typstyle" }

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.rust-analyzer.config.files]
watcher = "server"

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.svelteserver.config.configuration.typescript]
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes.enabled = true
inlayHints.enumMemberValues.enabled = true
inlayHints.parameterNames.enabled = "all"

[language-server.svelteserver.config.configuration.javascript]
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes.enabled = true
inlayHints.enumMemberValues.enabled = true
inlayHints.parameterNames.enabled = "all"

[language-server.typescript-language-server.config.typescript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true

[language-server.typescript-language-server.config.javascript.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.ocamllsp]
config = { inlayHints = { enable = true, typeHints = { enable = true }, parameterHints = { enable = true } } }

[language-server.basedpyright.config]
basedpyright.analysis.autoSearchPaths = true
basedpyright.analysis.diagnosticMode = "workspace"
basedpyright.analysis.useLibraryCodeForTypes = true
# Type checking strictness (can be "off", "basic", "standard", "strict")
basedpyright.analysis.typeCheckingMode = "standard"
basedpyright.analysis.diagnosticSeverityOverrides = {}

# -------------------------------
# Language Definitions
# -------------------------------

[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["ts", "tsx"]
auto-format = true
language-servers = ["deno-lsp", "typescript-language-server"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.ts"] }

[[language]]
name = "svelte"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.svelte"] }

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["js", "jsx"]
auto-format = true
language-servers = ["deno-lsp", "typescript-language-server"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.js"] }

[[language]]
name = "dune"
scope = "source.dune"
roots = ["dune-project"]
file-types = [{ glob = "dune-project" }, { glob = "dune" }]
comment-token = ";"
indent = { tab-width = 1, unit = " " }
grammar = "scheme"
auto-format = true
formatter = { command = "dune", args = ["format-dune-file"] }

# [[language]]
# name = "elixir"
# scope = "source.elixir"
# injection-regex = "(elixir|ex)"
# file-types = ["ex", "exs", { glob = "mix.lock" }]
# shebangs = ["elixir"]
# roots = ["mix.exs", "mix.lock"]
# comment-token = "#"
# language-servers = [ "elixir-ls" ]
# indent = { tab-width = 2, unit = "  " }

[[language]]
name = "elixir"
scope = "source.elixir"
file-types = ["ex", "exs", { glob = "mix.lock" }]
auto-format = true
# diagnostic-severity = "Hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
injection-regex = "(elixir|ex)"
shebangs = ["elixir"]
roots = ["mix.exs", "mix.lock"]
language-servers = [ "elixir-ls" ]


[[language]]
name = "markdown"
soft-wrap.enable = true
soft-wrap.wrap-indicator = ""
language-servers = ["marksman", "ltex-ls-plus"]
# soft-wrap.wrap-at-text-width = true

[[language]]
name = "iex"
scope = "source.iex"
injection-regex = "iex"
file-types = ["iex"]
comment-token = "#"

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typ(st)?"
file-types = ["typst", "typ"]
comment-token = "//"
soft-wrap.enable = true
soft-wrap.wrap-indicator = ""
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["tinymist"]
indent = { tab-width = 2, unit = "  " }

# -------------------------------
# Grammar Sources
# -------------------------------

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst", rev = "13863ddcbaa7b68ee6221cea2e3143415e64aea4" }

[[grammar]]
name = "jinja2"
source = { git = "https://github.com/varpeti/tree-sitter-jinja2", rev = "a533cd3c33aea6acb0f9bf9a56f35dcfe6a8eb53" }

[[grammar]]
name = "javascript"
source = { git = "https://github.com/tree-sitter/tree-sitter-javascript", rev = "f772967f7b7bc7c28f845be2420a38472b16a8e" }

[[grammar]]
name = "markdown"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-markdown", rev = "62516e8c78380e3b51d5b55727995d2c511436d8", subpath = "tree-sitter-markdown" }

[[grammar]]
name = "ocaml"
source = { git = "https://github.com/tree-sitter/tree-sitter-ocaml", rev = "9965d208337d88bbf1a38ad0b0fe49e5f5ec9677", subpath = "ocaml" }

[[grammar]]
name = "ocaml-interface"
source = { git = "https://github.com/tree-sitter/tree-sitter-ocaml", rev = "9965d208337d88bbf1a38ad0b0fe49e5f5ec9677", subpath = "interface" }

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "1f63b33efee17e833e0ea29266dd3d713e27e321" }

[[grammar]]
name = "typescript"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript", rev = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf", subpath = "typescript" }

[[grammar]]
name = "elixir"
source = { git = "https://github.com/elixir-lang/tree-sitter-elixir", rev = "02a6f7fd4be28dd94ee4dd2ca19cb777053ea74e" }

[[grammar]]
name = "iex"
source = { git = "https://github.com/elixir-lang/tree-sitter-iex", rev = "39f20bb51f502e32058684e893c0c0b00bb2332c" }

# -------------------------------
# Auto-Pairs Configuration
# -------------------------------

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
