---@class Gruvlight
---@field config GruvlightConfig
---@field palette GruvlightPalette
local Gruvlight = {}

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class GruvlightConfig
---@field bold boolean?
---@field dim_inactive boolean?
---@field inverse boolean?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field italic ItalicConfig?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
---@field strikethrough boolean?
---@field terminal_colors boolean?
---@field transparent_mode boolean?
---@field undercurl boolean?
---@field underline boolean?

local default_config = {
    terminal_colors = true,
    undercurl = true,
    underline = true,
    bold = true,
    italic = {
        strings = true,
        emphasis = true,
        comments = true,
        operators = false,
        folds = true,
    },
    strikethrough = true,
    invert_selection = false,
    invert_signs = false,
    invert_tabline = false,
    inverse = true,
    palette_overrides = {},
    overrides = {},
    dim_inactive = false,
    transparent_mode = false,
}

Gruvlight.config = vim.deepcopy(default_config)

-- main gruvlight color palette (only what's needed for DARK HARD)
---@class GruvlightPalette
-- main gruvlight color palette
---@class GruvlightPalette
Gruvlight.palette = {
    light0_hard     = "#ffffff",
    light0          = "#fbfbf5",
    light1          = "#f2f2ee",
    light2          = "#e6e6e2",
    light3          = "#d8d8d4",
    light4          = "#c4c4c0",

    dark0           = "#1f1f1f",
    dark1           = "#2e2e2e",
    dark2           = "#4a4a4a",
    dark3           = "#6a6a6a",
    dark4           = "#8a8a8a",

    bright_red      = "#d04632",
    bright_green    = "#8aa21f",
    bright_yellow   = "#d8ab1d",
    bright_blue     = "#5f87af",
    bright_purple   = "#b070a8",
    bright_aqua     = "#6ca58c",
    bright_orange   = "#e06b28",

    neutral_red     = "#b73525",
    neutral_green   = "#6d7f12",
    neutral_yellow  = "#b89616",
    neutral_blue    = "#3f6d89",
    neutral_purple  = "#8a5a90",
    neutral_aqua    = "#4f7f6a",

    dark_red_hard   = "#6b1f25",
    dark_green_hard = "#4a5c32",
    dark_aqua_hard  = "#334238",

    gray            = "#8e8e8e",
}


-- Build Gruvlight LIGHT color table.
local function get_colors()
    local p = Gruvlight.palette
    local config = Gruvlight.config

    -- allow user overrides
    for color, hex in pairs(config.palette_overrides) do
        p[color] = hex
    end

    ----------------------------------------------------------------------
    -- CHANGED: Light backgrounds + dark foregrounds
    ----------------------------------------------------------------------
    local colors = {
        -- backgrounds (LIGHT)
        bg0 = p.light0, -- main editor bg
        bg1 = p.light1,
        bg2 = p.light2,
        bg3 = p.light3,
        bg4 = p.light4,

        -- foregrounds (dark ramp)
        fg0 = p.dark0,
        fg1 = p.dark1,
        fg2 = p.dark2,
        fg3 = p.dark3,
        fg4 = p.dark4,

        -- accents (unchanged)
        red = p.bright_red,
        green = p.bright_green,
        yellow = p.bright_yellow,
        blue = p.bright_blue,
        purple = p.bright_purple,
        aqua = p.bright_aqua,
        orange = p.bright_orange,

        -- neutrals
        neutral_red = p.neutral_red,
        neutral_green = p.neutral_green,
        neutral_yellow = p.neutral_yellow,
        neutral_blue = p.neutral_blue,
        neutral_purple = p.neutral_purple,
        neutral_aqua = p.neutral_aqua,

        -- diff (unchanged)
        dark_red = p.dark_red_hard,
        dark_green = p.dark_green_hard,
        dark_aqua = p.dark_aqua_hard,

        gray = p.gray,
    }

    return colors
end

local function get_groups()
    local colors = get_colors()
    local config = Gruvlight.config

    if config.terminal_colors then
        local term_colors = {
            colors.bg0,
            colors.neutral_red,
            colors.neutral_green,
            colors.neutral_yellow,
            colors.neutral_blue,
            colors.neutral_purple,
            colors.neutral_aqua,
            colors.fg4,
            colors.gray,
            colors.red,
            colors.green,
            colors.yellow,
            colors.blue,
            colors.purple,
            colors.aqua,
            colors.fg1,
        }
        for index, value in ipairs(term_colors) do
            vim.g["terminal_color_" .. index - 1] = value
        end
    end

    local groups = {
        GruvlightFg0 = { fg = colors.fg0 },
        GruvlightFg1 = { fg = colors.fg1 },
        GruvlightFg2 = { fg = colors.fg2 },
        GruvlightFg3 = { fg = colors.fg3 },
        GruvlightFg4 = { fg = colors.fg4 },
        GruvlightWhite = { fg = colors.fg0 }, -- provide this as it’s referenced later
        GruvlightGray = { fg = colors.gray },
        GruvlightBg0 = { fg = colors.bg0 },
        GruvlightBg1 = { fg = colors.bg1 },
        GruvlightBg2 = { fg = colors.bg2 },
        GruvlightBg3 = { fg = colors.bg3 },
        GruvlightBg4 = { fg = colors.bg4 },
        GruvlightRed = { fg = colors.red },
        GruvlightRedBold = { fg = colors.red, bold = config.bold },
        GruvlightGreen = { fg = colors.green },
        GruvlightGreenBold = { fg = colors.green, bold = config.bold },
        GruvlightYellow = { fg = colors.yellow },
        GruvlightYellowBold = { fg = colors.yellow, bold = config.bold },
        GruvlightBlue = { fg = colors.blue },
        GruvlightBlueBold = { fg = colors.blue, bold = config.bold },
        GruvlightPurple = { fg = colors.purple },
        GruvlightPurpleBold = { fg = colors.purple, bold = config.bold },
        GruvlightAqua = { fg = colors.aqua },
        GruvlightAquaBold = { fg = colors.aqua, bold = config.bold },
        GruvlightOrange = { fg = colors.orange },
        GruvlightOrangeBold = { fg = colors.orange, bold = config.bold },
        GruvlightRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
            or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
        GruvlightGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
            or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
        GruvlightYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
            or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
        GruvlightBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
            or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
        GruvlightPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
            or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
        GruvlightAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
            or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
        GruvlightOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
            or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
        GruvlightRedUnderline = { undercurl = config.undercurl, sp = colors.red },
        GruvlightGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
        GruvlightYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
        GruvlightBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
        GruvlightPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
        GruvlightAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
        GruvlightOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
        Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
        NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
        NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
        CursorLine = { bg = colors.bg1 },
        CursorColumn = { link = "CursorLine" },
        TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
        TabLine = { link = "TabLineFill" },
        MatchParen = { bg = colors.bg3, bold = config.bold },
        ColorColumn = { bg = colors.bg1 },
        Conceal = { fg = colors.blue },
        CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
        NonText = { link = "GruvlightBg2" },
        SpecialKey = { link = "GruvlightFg4" },
        Visual = { bg = colors.bg3, reverse = config.invert_selection },
        VisualNOS = { link = "Visual" },
        Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
        IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
        CurSearch = { link = "IncSearch" },
        QuickFixLine = { link = "GruvlightPurple" },
        Underlined = { fg = colors.blue, underline = config.underline },
        StatusLine = { fg = colors.fg1, bg = colors.bg2 },
        StatusLineNC = { fg = colors.fg4, bg = colors.bg1 },
        WinBar = { fg = colors.fg4, bg = colors.bg0 },
        WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
        WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
        WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
        Directory = { link = "GruvlightGreenBold" },
        Title = { link = "GruvlightGreenBold" },
        ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        MoreMsg = { link = "GruvlightYellowBold" },
        ModeMsg = { link = "GruvlightYellowBold" },
        Question = { link = "GruvlightOrangeBold" },
        WarningMsg = { link = "GruvlightRedBold" },
        LineNr = { fg = colors.bg4 },
        SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
        Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
        FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
        Cursor = { reverse = config.inverse },
        vCursor = { link = "Cursor" },
        iCursor = { link = "Cursor" },
        lCursor = { link = "Cursor" },
        Special = { link = "GruvlightOrange" },
        Comment = { fg = colors.gray, italic = config.italic.comments },
        Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
        Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
        Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
        Statement = { link = "GruvlightRed" },
        Conditional = { link = "GruvlightRed" },
        Repeat = { link = "GruvlightRed" },
        Label = { link = "GruvlightRed" },
        Exception = { link = "GruvlightRed" },
        Operator = { fg = colors.orange, italic = config.italic.operators },
        Keyword = { link = "GruvlightRed" },
        Identifier = { link = "GruvlightBlue" },
        Function = { link = "GruvlightGreenBold" },
        PreProc = { link = "GruvlightAqua" },
        Include = { link = "GruvlightAqua" },
        Define = { link = "GruvlightAqua" },
        Macro = { link = "GruvlightAqua" },
        PreCondit = { link = "GruvlightAqua" },
        Constant = { link = "GruvlightPurple" },
        Character = { link = "GruvlightPurple" },
        String = { fg = colors.green, italic = config.italic.strings },
        Boolean = { link = "GruvlightPurple" },
        Number = { link = "GruvlightPurple" },
        Float = { link = "GruvlightPurple" },
        Type = { link = "GruvlightYellow" },
        StorageClass = { link = "GruvlightOrange" },
        Structure = { link = "GruvlightAqua" },
        Typedef = { link = "GruvlightYellow" },
        Pmenu = { fg = colors.fg1, bg = colors.bg2 },
        PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
        PmenuSbar = { bg = colors.bg2 },
        PmenuThumb = { bg = colors.bg4 },
        DiffDelete = { bg = colors.dark_red },
        DiffAdd = { bg = colors.dark_green },
        DiffChange = { bg = colors.dark_aqua },
        DiffText = { bg = colors.yellow, fg = colors.bg0 },
        SpellCap = { link = "GruvlightBlueUnderline" },
        SpellBad = { link = "GruvlightRedUnderline" },
        SpellLocal = { link = "GruvlightAquaUnderline" },
        SpellRare = { link = "GruvlightPurpleUnderline" },
        Whitespace = { fg = colors.bg2 },
        Delimiter = { link = "GruvlightOrange" },
        EndOfBuffer = { link = "NonText" },

        DiagnosticError = { link = "GruvlightRed" },
        DiagnosticWarn = { link = "GruvlightYellow" },
        DiagnosticInfo = { link = "GruvlightBlue" },
        DiagnosticDeprecated = { strikethrough = config.strikethrough },
        DiagnosticHint = { link = "GruvlightAqua" },
        DiagnosticOk = { link = "GruvlightGreen" },
        DiagnosticSignError = { link = "GruvlightRedSign" },
        DiagnosticSignWarn = { link = "GruvlightYellowSign" },
        DiagnosticSignInfo = { link = "GruvlightBlueSign" },
        DiagnosticSignHint = { link = "GruvlightAquaSign" },
        DiagnosticSignOk = { link = "GruvlightGreenSign" },
        DiagnosticUnderlineError = { link = "GruvlightRedUnderline" },
        DiagnosticUnderlineWarn = { link = "GruvlightYellowUnderline" },
        DiagnosticUnderlineInfo = { link = "GruvlightBlueUnderline" },
        DiagnosticUnderlineHint = { link = "GruvlightAquaUnderline" },
        DiagnosticUnderlineOk = { link = "GruvlightGreenUnderline" },
        DiagnosticFloatingError = { link = "GruvlightRed" },
        DiagnosticFloatingWarn = { link = "GruvlightOrange" },
        DiagnosticFloatingInfo = { link = "GruvlightBlue" },
        DiagnosticFloatingHint = { link = "GruvlightAqua" },
        DiagnosticFloatingOk = { link = "GruvlightGreen" },
        DiagnosticVirtualTextError = { link = "GruvlightRed" },
        DiagnosticVirtualTextWarn = { link = "GruvlightYellow" },
        DiagnosticVirtualTextInfo = { link = "GruvlightBlue" },
        DiagnosticVirtualTextHint = { link = "GruvlightAqua" },
        DiagnosticVirtualTextOk = { link = "GruvlightGreen" },

        LspReferenceRead = { link = "GruvlightYellowBold" },
        LspReferenceTarget = { link = "Visual" },
        LspReferenceText = { link = "GruvlightYellowBold" },
        LspReferenceWrite = { link = "GruvlightOrangeBold" },
        LspCodeLens = { link = "GruvlightGray" },
        LspSignatureActiveParameter = { link = "Search" },

        gitcommitSelectedFile = { link = "GruvlightGreen" },
        gitcommitDiscardedFile = { link = "GruvlightRed" },
        GitSignsAdd = { link = "GruvlightGreen" },
        GitSignsChange = { link = "GruvlightOrange" },
        GitSignsDelete = { link = "GruvlightRed" },

        NvimTreeSymlink = { fg = colors.neutral_aqua },
        NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
        NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
        NvimTreeFileIcon = { fg = colors.light2 },
        NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
        NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
        NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
        NvimTreeImageFile = { fg = colors.neutral_purple },
        NvimTreeIndentMarker = { fg = colors.dark3 },
        NvimTreeGitDirty = { fg = colors.neutral_yellow },
        NvimTreeGitStaged = { fg = colors.neutral_yellow },
        NvimTreeGitMerge = { fg = colors.neutral_purple },
        NvimTreeGitRenamed = { fg = colors.neutral_purple },
        NvimTreeGitNew = { fg = colors.neutral_yellow },
        NvimTreeGitDeleted = { fg = colors.neutral_red },
        NvimTreeWindowPicker = { bg = colors.aqua },

        debugPC = { link = "DiffAdd" },
        debugBreakpoint = { link = "GruvlightRedSign" },

        StartifyBracket = { link = "GruvlightFg3" },
        StartifyFile = { link = "GruvlightFg1" },
        StartifyNumber = { link = "GruvlightBlue" },
        StartifyPath = { link = "GruvlightGray" },
        StartifySlash = { link = "GruvlightGray" },
        StartifySection = { link = "GruvlightYellow" },
        StartifySpecial = { link = "GruvlightBg2" },
        StartifyHeader = { link = "GruvlightOrange" },
        StartifyFooter = { link = "GruvlightBg2" },
        StartifyVar = { link = "StartifyPath" },
        StartifySelect = { link = "Title" },

        DirvishPathTail = { link = "GruvlightAqua" },
        DirvishArg = { link = "GruvlightYellow" },

        netrwDir = { link = "GruvlightAqua" },
        netrwClassify = { link = "GruvlightAqua" },
        netrwLink = { link = "GruvlightGray" },
        netrwSymLink = { link = "GruvlightFg1" },
        netrwExe = { link = "GruvlightYellow" },
        netrwComment = { link = "GruvlightGray" },
        netrwList = { link = "GruvlightBlue" },
        netrwHelpCmd = { link = "GruvlightAqua" },
        netrwCmdSep = { link = "GruvlightFg3" },
        netrwVersion = { link = "GruvlightGreen" },

        NERDTreeDir = { link = "GruvlightAqua" },
        NERDTreeDirSlash = { link = "GruvlightAqua" },
        NERDTreeOpenable = { link = "GruvlightOrange" },
        NERDTreeClosable = { link = "GruvlightOrange" },
        NERDTreeFile = { link = "GruvlightFg1" },
        NERDTreeExecFile = { link = "GruvlightYellow" },
        NERDTreeUp = { link = "GruvlightGray" },
        NERDTreeCWD = { link = "GruvlightGreen" },
        NERDTreeHelp = { link = "GruvlightFg1" },
        NERDTreeToggleOn = { link = "GruvlightGreen" },
        NERDTreeToggleOff = { link = "GruvlightRed" },

        CocErrorSign = { link = "GruvlightRedSign" },
        CocWarningSign = { link = "GruvlightOrangeSign" },
        CocInfoSign = { link = "GruvlightBlueSign" },
        CocHintSign = { link = "GruvlightAquaSign" },
        CocErrorFloat = { link = "GruvlightRed" },
        CocWarningFloat = { link = "GruvlightOrange" },
        CocInfoFloat = { link = "GruvlightBlue" },
        CocHintFloat = { link = "GruvlightAqua" },
        CocDiagnosticsError = { link = "GruvlightRed" },
        CocDiagnosticsWarning = { link = "GruvlightOrange" },
        CocDiagnosticsInfo = { link = "GruvlightBlue" },
        CocDiagnosticsHint = { link = "GruvlightAqua" },
        CocSearch = { link = "GruvlightBlue" },
        CocSelectedText = { link = "GruvlightRed" },
        CocMenuSel = { link = "PmenuSel" },
        CocCodeLens = { link = "GruvlightGray" },
        CocErrorHighlight = { link = "GruvlightRedUnderline" },
        CocWarningHighlight = { link = "GruvlightOrangeUnderline" },
        CocInfoHighlight = { link = "GruvlightBlueUnderline" },
        CocHintHighlight = { link = "GruvlightAquaUnderline" },

        SnacksPicker = { link = "GruvlightFg1" },
        SnacksPickerBorder = { link = "SnacksPicker" },
        SnacksPickerListCursorLine = { link = "CursorLine" },
        SnacksPickerMatch = { link = "GruvlightOrange" },
        SnacksPickerPrompt = { link = "GruvlightRed" },
        SnacksPickerTitle = { link = "SnacksPicker" },
        SnacksPickerDir = { link = "GruvlightGray" },
        SnacksPickerPathHidden = { link = "GruvlightGray" },
        SnacksPickerGitStatusUntracked = { link = "GruvlightGray" },
        SnacksPickerPathIgnored = { link = "GruvlightBg3" },

        TelescopeNormal = { link = "GruvlightFg1" },
        TelescopeSelection = { link = "CursorLine" },
        TelescopeSelectionCaret = { link = "GruvlightRed" },
        TelescopeMultiSelection = { link = "GruvlightGray" },
        TelescopeBorder = { link = "TelescopeNormal" },
        TelescopePromptBorder = { link = "TelescopeNormal" },
        TelescopeResultsBorder = { link = "TelescopeNormal" },
        TelescopePreviewBorder = { link = "TelescopeNormal" },
        TelescopeMatching = { link = "GruvlightOrange" },
        TelescopePromptPrefix = { link = "GruvlightRed" },
        TelescopePrompt = { link = "TelescopeNormal" },

        CmpItemAbbr = { link = "GruvlightFg0" },
        CmpItemAbbrDeprecated = { link = "GruvlightFg1" },
        CmpItemAbbrMatch = { link = "GruvlightBlueBold" },
        CmpItemAbbrMatchFuzzy = { link = "GruvlightBlueUnderline" },
        CmpItemMenu = { link = "GruvlightGray" },
        CmpItemKindText = { link = "GruvlightOrange" },
        CmpItemKindVariable = { link = "GruvlightOrange" },
        CmpItemKindMethod = { link = "GruvlightBlue" },
        CmpItemKindFunction = { link = "GruvlightBlue" },
        CmpItemKindConstructor = { link = "GruvlightYellow" },
        CmpItemKindUnit = { link = "GruvlightBlue" },
        CmpItemKindField = { link = "GruvlightBlue" },
        CmpItemKindClass = { link = "GruvlightYellow" },
        CmpItemKindInterface = { link = "GruvlightYellow" },
        CmpItemKindModule = { link = "GruvlightBlue" },
        CmpItemKindProperty = { link = "GruvlightBlue" },
        CmpItemKindValue = { link = "GruvlightOrange" },
        CmpItemKindEnum = { link = "GruvlightYellow" },
        CmpItemKindOperator = { link = "GruvlightYellow" },
        CmpItemKindKeyword = { link = "GruvlightPurple" },
        CmpItemKindEvent = { link = "GruvlightPurple" },
        CmpItemKindReference = { link = "GruvlightPurple" },
        CmpItemKindColor = { link = "GruvlightPurple" },
        CmpItemKindSnippet = { link = "GruvlightGreen" },
        CmpItemKindFile = { link = "GruvlightBlue" },
        CmpItemKindFolder = { link = "GruvlightBlue" },
        CmpItemKindEnumMember = { link = "GruvlightAqua" },
        CmpItemKindConstant = { link = "GruvlightOrange" },
        CmpItemKindStruct = { link = "GruvlightYellow" },
        CmpItemKindTypeParameter = { link = "GruvlightYellow" },

        BlinkCmpLabel = { link = "GruvlightFg0" },
        BlinkCmpLabelDeprecated = { link = "GruvlightFg1" },
        BlinkCmpLabelMatch = { link = "GruvlightBlueBold" },
        BlinkCmpLabelDetail = { link = "GruvlightGray" },
        BlinkCmpLabelDescription = { link = "GruvlightGray" },
        BlinkCmpKindText = { link = "GruvlightOrange" },
        BlinkCmpKindVariable = { link = "GruvlightOrange" },
        BlinkCmpKindMethod = { link = "GruvlightBlue" },
        BlinkCmpKindFunction = { link = "GruvlightBlue" },
        BlinkCmpKindConstructor = { link = "GruvlightYellow" },
        BlinkCmpKindUnit = { link = "GruvlightBlue" },
        BlinkCmpKindField = { link = "GruvlightBlue" },
        BlinkCmpKindClass = { link = "GruvlightYellow" },
        BlinkCmpKindInterface = { link = "GruvlightYellow" },
        BlinkCmpKindModule = { link = "GruvlightBlue" },
        BlinkCmpKindProperty = { link = "GruvlightBlue" },
        BlinkCmpKindValue = { link = "GruvlightOrange" },
        BlinkCmpKindEnum = { link = "GruvlightYellow" },
        BlinkCmpKindOperator = { link = "GruvlightYellow" },
        BlinkCmpKindKeyword = { link = "GruvlightPurple" },
        BlinkCmpKindEvent = { link = "GruvlightPurple" },
        BlinkCmpKindReference = { link = "GruvlightPurple" },
        BlinkCmpKindColor = { link = "GruvlightPurple" },
        BlinkCmpKindSnippet = { link = "GruvlightGreen" },
        BlinkCmpKindFile = { link = "GruvlightBlue" },
        BlinkCmpKindFolder = { link = "GruvlightBlue" },
        BlinkCmpKindEnumMember = { link = "GruvlightAqua" },
        BlinkCmpKindConstant = { link = "GruvlightOrange" },
        BlinkCmpKindStruct = { link = "GruvlightYellow" },
        BlinkCmpKindTypeParameter = { link = "GruvlightYellow" },
        BlinkCmpSource = { link = "GruvlightGray" },
        BlinkCmpGhostText = { link = "GruvlightBg4" },

        diffAdded = { link = "DiffAdd" },
        diffRemoved = { link = "DiffDelete" },
        diffChanged = { link = "DiffChange" },
        diffFile = { link = "GruvlightOrange" },
        diffNewFile = { link = "GruvlightYellow" },
        diffOldFile = { link = "GruvlightOrange" },
        diffLine = { link = "GruvlightBlue" },
        diffIndexLine = { link = "diffChanged" },

        NavicIconsFile = { link = "GruvlightBlue" },
        NavicIconsModule = { link = "GruvlightOrange" },
        NavicIconsNamespace = { link = "GruvlightBlue" },
        NavicIconsPackage = { link = "GruvlightAqua" },
        NavicIconsClass = { link = "GruvlightYellow" },
        NavicIconsMethod = { link = "GruvlightBlue" },
        NavicIconsProperty = { link = "GruvlightAqua" },
        NavicIconsField = { link = "GruvlightPurple" },
        NavicIconsConstructor = { link = "GruvlightBlue" },
        NavicIconsEnum = { link = "GruvlightPurple" },
        NavicIconsInterface = { link = "GruvlightGreen" },
        NavicIconsFunction = { link = "GruvlightBlue" },
        NavicIconsVariable = { link = "GruvlightPurple" },
        NavicIconsConstant = { link = "GruvlightOrange" },
        NavicIconsString = { link = "GruvlightGreen" },
        NavicIconsNumber = { link = "GruvlightOrange" },
        NavicIconsBoolean = { link = "GruvlightOrange" },
        NavicIconsArray = { link = "GruvlightOrange" },
        NavicIconsObject = { link = "GruvlightOrange" },
        NavicIconsKey = { link = "GruvlightAqua" },
        NavicIconsNull = { link = "GruvlightOrange" },
        NavicIconsEnumMember = { link = "GruvlightYellow" },
        NavicIconsStruct = { link = "GruvlightPurple" },
        NavicIconsEvent = { link = "GruvlightYellow" },
        NavicIconsOperator = { link = "GruvlightRed" },
        NavicIconsTypeParameter = { link = "GruvlightRed" },
        NavicText = { link = "GruvlightWhite" },
        NavicSeparator = { link = "GruvlightWhite" },

        htmlTag = { link = "GruvlightAquaBold" },
        htmlEndTag = { link = "GruvlightAquaBold" },
        htmlTagName = { link = "GruvlightBlue" },
        htmlArg = { link = "GruvlightOrange" },
        htmlTagN = { link = "GruvlightFg1" },
        htmlSpecialTagName = { link = "GruvlightBlue" },
        htmlLink = { fg = colors.fg4, underline = config.underline },
        htmlSpecialChar = { link = "GruvlightRed" },
        htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
        htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
        htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
        htmlBoldUnderlineItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true, underline = config.underline },
        htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
        htmlUnderlineItalic = { fg = colors.fg0, bg = colors.bg0, italic = true, underline = config.underline },
        htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },

        xmlTag = { link = "GruvlightAquaBold" },
        xmlEndTag = { link = "GruvlightAquaBold" },
        xmlTagName = { link = "GruvlightBlue" },
        xmlEqual = { link = "GruvlightBlue" },
        docbkKeyword = { link = "GruvlightAquaBold" },
        xmlDocTypeDecl = { link = "GruvlightGray" },
        xmlDocTypeKeyword = { link = "GruvlightPurple" },
        xmlCdataStart = { link = "GruvlightGray" },
        xmlCdataCdata = { link = "GruvlightPurple" },
        dtdFunction = { link = "GruvlightGray" },
        dtdTagName = { link = "GruvlightPurple" },
        xmlAttrib = { link = "GruvlightOrange" },
        xmlProcessingDelim = { link = "GruvlightGray" },
        dtdParamEntityPunct = { link = "GruvlightGray" },
        dtdParamEntityDPunct = { link = "GruvlightGray" },
        xmlAttribPunct = { link = "GruvlightGray" },
        xmlEntity = { link = "GruvlightRed" },
        xmlEntityPunct = { link = "GruvlightRed" },

        clojureKeyword = { link = "GruvlightBlue" },
        clojureCond = { link = "GruvlightOrange" },
        clojureSpecial = { link = "GruvlightOrange" },
        clojureDefine = { link = "GruvlightOrange" },
        clojureFunc = { link = "GruvlightYellow" },
        clojureRepeat = { link = "GruvlightYellow" },
        clojureCharacter = { link = "GruvlightAqua" },
        clojureStringEscape = { link = "GruvlightAqua" },
        clojureException = { link = "GruvlightRed" },
        clojureRegexp = { link = "GruvlightAqua" },
        clojureRegexpEscape = { link = "GruvlightAqua" },
        clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
        clojureRegexpMod = { link = "clojureRegexpCharClass" },
        clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
        clojureParen = { link = "GruvlightFg3" },
        clojureAnonArg = { link = "GruvlightYellow" },
        clojureVariable = { link = "GruvlightBlue" },
        clojureMacro = { link = "GruvlightOrange" },
        clojureMeta = { link = "GruvlightYellow" },
        clojureDeref = { link = "GruvlightYellow" },
        clojureQuote = { link = "GruvlightYellow" },
        clojureUnquote = { link = "GruvlightYellow" },

        cOperator = { link = "GruvlightPurple" },
        cppOperator = { link = "GruvlightPurple" },
        cStructure = { link = "GruvlightOrange" },

        pythonBuiltin = { link = "GruvlightOrange" },
        pythonBuiltinObj = { link = "GruvlightOrange" },
        pythonBuiltinFunc = { link = "GruvlightOrange" },
        pythonFunction = { link = "GruvlightAqua" },
        pythonDecorator = { link = "GruvlightRed" },
        pythonInclude = { link = "GruvlightBlue" },
        pythonImport = { link = "GruvlightBlue" },
        pythonRun = { link = "GruvlightBlue" },
        pythonCoding = { link = "GruvlightBlue" },
        pythonOperator = { link = "GruvlightRed" },
        pythonException = { link = "GruvlightRed" },
        pythonExceptions = { link = "GruvlightPurple" },
        pythonBoolean = { link = "GruvlightPurple" },
        pythonDot = { link = "GruvlightFg3" },
        pythonConditional = { link = "GruvlightRed" },
        pythonRepeat = { link = "GruvlightRed" },
        pythonDottedName = { link = "GruvlightGreenBold" },

        cssBraces = { link = "GruvlightBlue" },
        cssFunctionName = { link = "GruvlightYellow" },
        cssIdentifier = { link = "GruvlightOrange" },
        cssClassName = { link = "GruvlightGreen" },
        cssColor = { link = "GruvlightBlue" },
        cssSelectorOp = { link = "GruvlightBlue" },
        cssSelectorOp2 = { link = "GruvlightBlue" },
        cssImportant = { link = "GruvlightGreen" },
        cssVendor = { link = "GruvlightFg1" },
        cssTextProp = { link = "GruvlightAqua" },
        cssAnimationProp = { link = "GruvlightAqua" },
        cssUIProp = { link = "GruvlightYellow" },
        cssTransformProp = { link = "GruvlightAqua" },
        cssTransitionProp = { link = "GruvlightAqua" },
        cssPrintProp = { link = "GruvlightAqua" },
        cssPositioningProp = { link = "GruvlightYellow" },
        cssBoxProp = { link = "GruvlightAqua" },
        cssFontDescriptorProp = { link = "GruvlightAqua" },
        cssFlexibleBoxProp = { link = "GruvlightAqua" },
        cssBorderOutlineProp = { link = "GruvlightAqua" },
        cssBackgroundProp = { link = "GruvlightAqua" },
        cssMarginProp = { link = "GruvlightAqua" },
        cssListProp = { link = "GruvlightAqua" },
        cssTableProp = { link = "GruvlightAqua" },
        cssFontProp = { link = "GruvlightAqua" },
        cssPaddingProp = { link = "GruvlightAqua" },
        cssDimensionProp = { link = "GruvlightAqua" },
        cssRenderProp = { link = "GruvlightAqua" },
        cssColorProp = { link = "GruvlightAqua" },
        cssGeneratedContentProp = { link = "GruvlightAqua" },

        javaScriptBraces = { link = "GruvlightFg1" },
        javaScriptFunction = { link = "GruvlightAqua" },
        javaScriptIdentifier = { link = "GruvlightRed" },
        javaScriptMember = { link = "GruvlightBlue" },
        javaScriptNumber = { link = "GruvlightPurple" },
        javaScriptNull = { link = "GruvlightPurple" },
        javaScriptParens = { link = "GruvlightFg3" },

        typescriptReserved = { link = "GruvlightAqua" },
        typescriptLabel = { link = "GruvlightAqua" },
        typescriptFuncKeyword = { link = "GruvlightAqua" },
        typescriptIdentifier = { link = "GruvlightOrange" },
        typescriptBraces = { link = "GruvlightFg1" },
        typescriptEndColons = { link = "GruvlightFg1" },
        typescriptDOMObjects = { link = "GruvlightFg1" },
        typescriptAjaxMethods = { link = "GruvlightFg1" },
        typescriptLogicSymbols = { link = "GruvlightFg1" },
        typescriptDocSeeTag = { link = "Comment" },
        typescriptDocParam = { link = "Comment" },
        typescriptDocTags = { link = "vimCommentTitle" },
        typescriptGlobalObjects = { link = "GruvlightFg1" },
        typescriptParens = { link = "GruvlightFg3" },
        typescriptOpSymbols = { link = "GruvlightFg3" },
        typescriptHtmlElemProperties = { link = "GruvlightFg1" },
        typescriptNull = { link = "GruvlightPurple" },
        typescriptInterpolationDelimiter = { link = "GruvlightAqua" },

        purescriptModuleKeyword = { link = "GruvlightAqua" },
        purescriptModuleName = { link = "GruvlightFg1" },
        purescriptWhere = { link = "GruvlightAqua" },
        purescriptDelimiter = { link = "GruvlightFg4" },
        purescriptType = { link = "GruvlightFg1" },
        purescriptImportKeyword = { link = "GruvlightAqua" },
        purescriptHidingKeyword = { link = "GruvlightAqua" },
        purescriptAsKeyword = { link = "GruvlightAqua" },
        purescriptStructure = { link = "GruvlightAqua" },
        purescriptOperator = { link = "GruvlightBlue" },
        purescriptTypeVar = { link = "GruvlightFg1" },
        purescriptConstructor = { link = "GruvlightFg1" },
        purescriptFunction = { link = "GruvlightFg1" },
        purescriptConditional = { link = "GruvlightOrange" },
        purescriptBacktick = { link = "GruvlightOrange" },

        coffeeExtendedOp = { link = "GruvlightFg3" },
        coffeeSpecialOp = { link = "GruvlightFg3" },
        coffeeCurly = { link = "GruvlightOrange" },
        coffeeParen = { link = "GruvlightFg3" },
        coffeeBracket = { link = "GruvlightOrange" },

        rubyStringDelimiter = { link = "GruvlightGreen" },
        rubyInterpolationDelimiter = { link = "GruvlightAqua" },
        rubyDefinedOperator = { link = "rubyKeyword" },

        objcTypeModifier = { link = "GruvlightRed" },
        objcDirective = { link = "GruvlightBlue" },

        goDirective = { link = "GruvlightAqua" },
        goConstants = { link = "GruvlightPurple" },
        goDeclaration = { link = "GruvlightRed" },
        goDeclType = { link = "GruvlightBlue" },
        goBuiltins = { link = "GruvlightOrange" },

        luaIn = { link = "GruvlightRed" },
        luaFunction = { link = "GruvlightAqua" },
        luaTable = { link = "GruvlightOrange" },

        moonSpecialOp = { link = "GruvlightFg3" },
        moonExtendedOp = { link = "GruvlightFg3" },
        moonFunction = { link = "GruvlightFg3" },
        moonObject = { link = "GruvlightYellow" },

        javaAnnotation = { link = "GruvlightBlue" },
        javaDocTags = { link = "GruvlightAqua" },
        javaCommentTitle = { link = "vimCommentTitle" },
        javaParen = { link = "GruvlightFg3" },
        javaParen1 = { link = "GruvlightFg3" },
        javaParen2 = { link = "GruvlightFg3" },
        javaParen3 = { link = "GruvlightFg3" },
        javaParen4 = { link = "GruvlightFg3" },
        javaParen5 = { link = "GruvlightFg3" },
        javaOperator = { link = "GruvlightOrange" },
        javaVarArg = { link = "GruvlightGreen" },

        elixirDocString = { link = "Comment" },
        elixirStringDelimiter = { link = "GruvlightGreen" },
        elixirInterpolationDelimiter = { link = "GruvlightAqua" },
        elixirModuleDeclaration = { link = "GruvlightYellow" },

        scalaNameDefinition = { link = "GruvlightFg1" },
        scalaCaseFollowing = { link = "GruvlightFg1" },
        scalaCapitalWord = { link = "GruvlightFg1" },
        scalaTypeExtension = { link = "GruvlightFg1" },
        scalaKeyword = { link = "GruvlightRed" },
        scalaKeywordModifier = { link = "GruvlightRed" },
        scalaSpecial = { link = "GruvlightAqua" },
        scalaOperator = { link = "GruvlightFg1" },
        scalaTypeDeclaration = { link = "GruvlightYellow" },
        scalaTypeTypePostDeclaration = { link = "GruvlightYellow" },
        scalaInstanceDeclaration = { link = "GruvlightFg1" },
        scalaInterpolation = { link = "GruvlightAqua" },

        markdownItalic = { fg = colors.fg3, italic = true },
        markdownBold = { fg = colors.fg3, bold = config.bold },
        markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
        markdownH1 = { link = "GruvlightGreenBold" },
        markdownH2 = { link = "GruvlightGreenBold" },
        markdownH3 = { link = "GruvlightYellowBold" },
        markdownH4 = { link = "GruvlightYellowBold" },
        markdownH5 = { link = "GruvlightYellow" },
        markdownH6 = { link = "GruvlightYellow" },
        markdownCode = { link = "GruvlightAqua" },
        markdownCodeBlock = { link = "GruvlightAqua" },
        markdownCodeDelimiter = { link = "GruvlightAqua" },
        markdownBlockquote = { link = "GruvlightGray" },
        markdownListMarker = { link = "GruvlightGray" },
        markdownOrderedListMarker = { link = "GruvlightGray" },
        markdownRule = { link = "GruvlightGray" },
        markdownHeadingRule = { link = "GruvlightGray" },
        markdownUrlDelimiter = { link = "GruvlightFg3" },
        markdownLinkDelimiter = { link = "GruvlightFg3" },
        markdownLinkTextDelimiter = { link = "GruvlightFg3" },
        markdownHeadingDelimiter = { link = "GruvlightOrange" },
        markdownUrl = { link = "GruvlightPurple" },
        markdownUrlTitleDelimiter = { link = "GruvlightGreen" },
        markdownLinkText = { fg = colors.gray, underline = config.underline },
        markdownIdDeclaration = { link = "markdownLinkText" },

        haskellType = { link = "GruvlightBlue" },
        haskellIdentifier = { link = "GruvlightAqua" },
        haskellSeparator = { link = "GruvlightFg4" },
        haskellDelimiter = { link = "GruvlightOrange" },
        haskellOperators = { link = "GruvlightPurple" },
        haskellBacktick = { link = "GruvlightOrange" },
        haskellStatement = { link = "GruvlightPurple" },
        haskellConditional = { link = "GruvlightPurple" },
        haskellLet = { link = "GruvlightRed" },
        haskellDefault = { link = "GruvlightRed" },
        haskellWhere = { link = "GruvlightRed" },
        haskellBottom = { link = "GruvlightRedBold" },
        haskellImportKeywords = { link = "GruvlightPurpleBold" },
        haskellDeclKeyword = { link = "GruvlightOrange" },
        haskellDecl = { link = "GruvlightOrange" },
        haskellDeriving = { link = "GruvlightPurple" },
        haskellAssocType = { link = "GruvlightAqua" },
        haskellNumber = { link = "GruvlightAqua" },
        haskellPragma = { link = "GruvlightRedBold" },
        haskellTH = { link = "GruvlightAquaBold" },
        haskellForeignKeywords = { link = "GruvlightGreen" },
        haskellKeyword = { link = "GruvlightRed" },
        haskellFloat = { link = "GruvlightAqua" },
        haskellInfix = { link = "GruvlightPurple" },
        haskellQuote = { link = "GruvlightGreenBold" },
        haskellShebang = { link = "GruvlightYellowBold" },
        haskellLiquid = { link = "GruvlightPurpleBold" },
        haskellQuasiQuoted = { link = "GruvlightBlueBold" },
        haskellRecursiveDo = { link = "GruvlightPurple" },
        haskellQuotedType = { link = "GruvlightRed" },
        haskellPreProc = { link = "GruvlightFg4" },
        haskellTypeRoles = { link = "GruvlightRedBold" },
        haskellTypeForall = { link = "GruvlightRed" },
        haskellPatternKeyword = { link = "GruvlightBlue" },

        jsonKeyword = { link = "GruvlightGreen" },
        jsonQuote = { link = "GruvlightGreen" },
        jsonBraces = { link = "GruvlightFg1" },
        jsonString = { link = "GruvlightFg1" },

        mailQuoted1 = { link = "GruvlightAqua" },
        mailQuoted2 = { link = "GruvlightPurple" },
        mailQuoted3 = { link = "GruvlightYellow" },
        mailQuoted4 = { link = "GruvlightGreen" },
        mailQuoted5 = { link = "GruvlightRed" },
        mailQuoted6 = { link = "GruvlightOrange" },
        mailSignature = { link = "Comment" },

        csBraces = { link = "GruvlightFg1" },
        csEndColon = { link = "GruvlightFg1" },
        csLogicSymbols = { link = "GruvlightFg1" },
        csParens = { link = "GruvlightFg3" },
        csOpSymbols = { link = "GruvlightFg3" },
        csInterpolationDelimiter = { link = "GruvlightFg3" },
        csInterpolationAlignDel = { link = "GruvlightAquaBold" },
        csInterpolationFormat = { link = "GruvlightAqua" },
        csInterpolationFormatDel = { link = "GruvlightAquaBold" },

        rustSigil = { link = "GruvlightOrange" },
        rustEscape = { link = "GruvlightAqua" },
        rustStringContinuation = { link = "GruvlightAqua" },
        rustEnum = { link = "GruvlightAqua" },
        rustStructure = { link = "GruvlightAqua" },
        rustModPathSep = { link = "GruvlightFg2" },
        rustCommentLineDoc = { link = "Comment" },
        rustDefault = { link = "GruvlightAqua" },

        ocamlOperator = { link = "GruvlightFg1" },
        ocamlKeyChar = { link = "GruvlightOrange" },
        ocamlArrow = { link = "GruvlightOrange" },
        ocamlInfixOpKeyword = { link = "GruvlightRed" },
        ocamlConstructor = { link = "GruvlightOrange" },

        LspSagaCodeActionTitle = { link = "Title" },
        LspSagaCodeActionBorder = { link = "GruvlightFg1" },
        LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
        LspSagaLspFinderBorder = { link = "GruvlightFg1" },
        LspSagaAutoPreview = { link = "GruvlightOrange" },
        TargetWord = { fg = colors.blue, bold = config.bold },
        FinderSeparator = { link = "GruvlightAqua" },
        LspSagaDefPreviewBorder = { link = "GruvlightBlue" },
        LspSagaHoverBorder = { link = "GruvlightOrange" },
        LspSagaRenameBorder = { link = "GruvlightBlue" },
        LspSagaDiagnosticSource = { link = "GruvlightOrange" },
        LspSagaDiagnosticBorder = { link = "GruvlightPurple" },
        LspSagaDiagnosticHeader = { link = "GruvlightGreen" },
        LspSagaSignatureHelpBorder = { link = "GruvlightGreen" },
        SagaShadow = { link = "GruvlightBg0" },

        DashboardShortCut = { link = "GruvlightOrange" },
        DashboardHeader = { link = "GruvlightAqua" },
        DashboardCenter = { link = "GruvlightYellow" },
        DashboardFooter = { fg = colors.purple, italic = true },

        MasonHighlight = { link = "GruvlightAqua" },
        MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
        MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
        MasonHighlightSecondary = { fg = colors.yellow },
        MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
        MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
        MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
        MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
        MasonMuted = { fg = colors.fg4 },
        MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
        MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },

        LspInlayHint = { link = "comment" },

        CarbonFile = { link = "GruvlightFg1" },
        CarbonExe = { link = "GruvlightYellow" },
        CarbonSymlink = { link = "GruvlightAqua" },
        CarbonBrokenSymlink = { link = "GruvlightRed" },
        CarbonIndicator = { link = "GruvlightGray" },
        CarbonDanger = { link = "GruvlightRed" },
        CarbonPending = { link = "GruvlightYellow" },

        NoiceCursor = { link = "TermCursor" },
        NoiceCmdlinePopupBorder = { fg = colors.blue, bg = nil },
        NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
        NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
        NoiceCmdlinePopupBorderSearch = { fg = colors.yellow, bg = nil },
        NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },

        NotifyDEBUGBorder = { link = "GruvlightBlue" },
        NotifyDEBUGIcon = { link = "GruvlightBlue" },
        NotifyDEBUGTitle = { link = "GruvlightBlue" },
        NotifyERRORBorder = { link = "GruvlightRed" },
        NotifyERRORIcon = { link = "GruvlightRed" },
        NotifyERRORTitle = { link = "GruvlightRed" },
        NotifyINFOBorder = { link = "GruvlightAqua" },
        NotifyINFOIcon = { link = "GruvlightAqua" },
        NotifyINFOTitle = { link = "GruvlightAqua" },
        NotifyTRACEBorder = { link = "GruvlightGreen" },
        NotifyTRACEIcon = { link = "GruvlightGreen" },
        NotifyTRACETitle = { link = "GruvlightGreen" },
        NotifyWARNBorder = { link = "GruvlightYellow" },
        NotifyWARNIcon = { link = "GruvlightYellow" },
        NotifyWARNTitle = { link = "GruvlightYellow" },

        IlluminatedWordText = { link = "LspReferenceText" },
        IlluminatedWordRead = { link = "LspReferenceRead" },
        IlluminatedWordWrite = { link = "LspReferenceWrite" },

        TSRainbowRed = { fg = colors.red },
        TSRainbowOrange = { fg = colors.orange },
        TSRainbowYellow = { fg = colors.yellow },
        TSRainbowGreen = { fg = colors.green },
        TSRainbowBlue = { fg = colors.blue },
        TSRainbowViolet = { fg = colors.purple },
        TSRainbowCyan = { fg = colors.aqua },

        RainbowDelimiterRed = { fg = colors.red },
        RainbowDelimiterOrange = { fg = colors.orange },
        RainbowDelimiterYellow = { fg = colors.yellow },
        RainbowDelimiterGreen = { fg = colors.green },
        RainbowDelimiterBlue = { fg = colors.blue },
        RainbowDelimiterViolet = { fg = colors.purple },
        RainbowDelimiterCyan = { fg = colors.aqua },

        DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
        DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },

        DapUIBreakpointsCurrentLine = { link = "GruvlightYellow" },
        DapUIBreakpointsDisabledLine = { link = "GruvlightGray" },
        DapUIBreakpointsInfo = { link = "GruvlightAqua" },
        DapUIBreakpointsLine = { link = "GruvlightYellow" },
        DapUIBreakpointsPath = { link = "GruvlightBlue" },
        DapUICurrentFrameName = { link = "GruvlightPurple" },
        DapUIDecoration = { link = "GruvlightPurple" },
        DapUIEndofBuffer = { link = "EndOfBuffer" },
        DapUIFloatBorder = { link = "GruvlightAqua" },
        DapUILineNumber = { link = "GruvlightYellow" },
        DapUIModifiedValue = { link = "GruvlightRed" },
        DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
        DapUIRestart = { fg = colors.green, bg = colors.bg1 },
        DapUIScope = { link = "GruvlightBlue" },
        DapUISource = { link = "GruvlightFg1" },
        DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
        DapUIStop = { fg = colors.red, bg = colors.bg1 },
        DapUIStoppedThread = { link = "GruvlightBlue" },
        DapUIThread = { link = "GruvlightBlue" },
        DapUIType = { link = "GruvlightOrange" },
        DapUIUnavailable = { link = "GruvlightGray" },
        DapUIWatchesEmpty = { link = "GruvlightGray" },
        DapUIWatchesError = { link = "GruvlightRed" },
        DapUIWatchesValue = { link = "GruvlightYellow" },
        DapUIWinSelect = { link = "GruvlightYellow" },

        NeogitDiffDelete = { link = "DiffDelete" },
        NeogitDiffAdd = { link = "DiffAdd" },
        NeogitHunkHeader = { link = "WinBar" },
        NeogitHunkHeaderHighlight = { link = "WinBarNC" },

        DiffviewStatusModified = { link = "GruvlightGreenBold" },
        DiffviewFilePanelInsertions = { link = "GruvlightGreenBold" },
        DiffviewFilePanelDeletions = { link = "GruvlightRedBold" },

        MiniAnimateCursor = { reverse = true, nocombine = true },
        MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },

        MiniClueBorder = { link = "FloatBorder" },
        MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
        MiniClueDescSingle = { link = "NormalFloat" },
        MiniClueNextKey = { link = "DiagnosticFloatingHint" },
        MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
        MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
        MiniClueTitle = { link = "FloatTitle" },

        MiniCompletionActiveParameter = { underline = true },
        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },

        MiniDepsChangeAdded = { link = "GruvlightGreen" },
        MiniDepsChangeRemoved = { link = "GruvlightRed" },
        MiniDepsHint = { link = "DiagnosticHint" },
        MiniDepsInfo = { link = "DiagnosticInfo" },
        MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
        MiniDepsPlaceholder = { link = "Comment" },
        MiniDepsTitle = { link = "Title" },
        MiniDepsTitleError = { link = "DiffDelete" },
        MiniDepsTitleSame = { link = "DiffChange" },
        MiniDepsTitleUpdate = { link = "DiffAdd" },

        MiniDiffOverAdd = { link = "DiffAdd" },
        MiniDiffOverChange = { link = "DiffText" },
        MiniDiffOverContext = { link = "DiffChange" },
        MiniDiffOverDelete = { link = "DiffDelete" },
        MiniDiffSignAdd = { link = "GruvlightGreen" },
        MiniDiffSignChange = { link = "GruvlightAqua" },
        MiniDiffSignDelete = { link = "GruvlightRed" },

        MiniFilesBorder = { link = "FloatBorder" },
        MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
        MiniFilesCursorLine = { bg = colors.bg2 },
        MiniFilesDirectory = { link = "Directory" },
        MiniFilesFile = { link = "GruvlightFg1" },
        MiniFilesNormal = { link = "NormalFloat" },
        MiniFilesTitle = { link = "FloatTitle" },
        MiniFilesTitleFocused = { link = "GruvlightOrangeBold" },

        MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
        MiniHipatternsNote = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
        MiniHipatternsTodo = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },

        MiniIconsAzure = { link = "GruvlightBlue" },
        MiniIconsBlue = { link = "GruvlightBlue" },
        MiniIconsCyan = { link = "GruvlightAqua" },
        MiniIconsGreen = { link = "GruvlightGreen" },
        MiniIconsGrey = { link = "GruvlightFg0" },
        MiniIconsOrange = { link = "GruvlightOrange" },
        MiniIconsPurple = { link = "GruvlightPurple" },
        MiniIconsRed = { link = "GruvlightRed" },
        MiniIconsYellow = { link = "GruvlightYellow" },

        MiniIndentscopeSymbol = { link = "GruvlightGray" },
        MiniIndentscopeSymbolOff = { link = "GruvlightYellow" },

        MiniJump = { link = "GruvlightOrangeUnderline" },
        MiniJump2dDim = { link = "GruvlightGray" },
        MiniJump2dSpot = { fg = colors.orange, bold = config.bold, nocombine = true },
        MiniJump2dSpotAhead = { fg = colors.aqua, bg = colors.bg0, nocombine = true },
        MiniJump2dSpotUnique = { fg = colors.yellow, bold = config.bold, nocombine = true },

        MiniMapNormal = { link = "NormalFloat" },
        MiniMapSymbolCount = { link = "Special" },
        MiniMapSymbolLine = { link = "Title" },
        MiniMapSymbolView = { link = "Delimiter" },

        MiniNotifyBorder = { link = "FloatBorder" },
        MiniNotifyNormal = { link = "NormalFloat" },
        MiniNotifyTitle = { link = "FloatTitle" },

        MiniOperatorsExchangeFrom = { link = "IncSearch" },

        MiniPickBorder = { link = "FloatBorder" },
        MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
        MiniPickBorderText = { link = "FloatTitle" },
        MiniPickIconDirectory = { link = "Directory" },
        MiniPickIconFile = { link = "MiniPickNormal" },
        MiniPickHeader = { link = "DiagnosticFloatingHint" },
        MiniPickMatchCurrent = { bg = colors.bg2 },
        MiniPickMatchMarked = { link = "Visual" },
        MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
        MiniPickNormal = { link = "NormalFloat" },
        MiniPickPreviewLine = { link = "CursorLine" },
        MiniPickPreviewRegion = { link = "IncSearch" },
        MiniPickPrompt = { link = "DiagnosticFloatingInfo" },

        MiniStarterCurrent = { nocombine = true },
        MiniStarterFooter = { link = "GruvlightGray" },
        MiniStarterHeader = { link = "Title" },
        MiniStarterInactive = { link = "Comment" },
        MiniStarterItem = { link = "Normal" },
        MiniStarterItemBullet = { link = "Delimiter" },
        MiniStarterItemPrefix = { link = "WarningMsg" },
        MiniStarterSection = { link = "Delimiter" },
        MiniStarterQuery = { link = "MoreMsg" },

        MiniStatuslineDevinfo = { link = "StatusLine" },
        MiniStatuslineFileinfo = { link = "StatusLine" },
        MiniStatuslineFilename = { link = "StatusLineNC" },
        MiniStatuslineInactive = { link = "StatusLineNC" },
        MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, nocombine = true },
        MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.blue, bold = config.bold, nocombine = true },
        MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1, bold = config.bold, nocombine = true },
        MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.aqua, bold = config.bold, nocombine = true },
        MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.red, bold = config.bold, nocombine = true },
        MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.green, bold = config.bold, nocombine = true },

        MiniSurround = { link = "IncSearch" },

        MiniTablineCurrent = { fg = colors.green, bg = colors.bg1, bold = config.bold, reverse = config.invert_tabline },
        MiniTablineFill = { link = "TabLineFill" },
        MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        MiniTablineModifiedCurrent = { fg = colors.bg1, bg = colors.green, bold = config.bold, reverse = config.invert_tabline },
        MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4, reverse = config.invert_tabline },
        MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1, reverse = config.invert_tabline },
        MiniTablineTabpagesection = { link = "Search" },
        MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1, reverse = config.invert_tabline },

        MiniTestEmphasis = { bold = config.bold },
        MiniTestFail = { link = "GruvlightRedBold" },
        MiniTestPass = { link = "GruvlightGreenBold" },

        MiniTrailspace = { bg = colors.red },

        WhichKeyTitle = { link = "NormalFloat" },

        NeoTreeFloatBorder = { link = "GruvlightGray" },
        NeoTreeTitleBar = { fg = colors.fg1, bg = colors.bg2 },
        NeoTreeDirectoryIcon = { link = "GruvlightGreen" },
        NeoTreeDirectoryName = { link = "GruvlightGreenBold" },

        -- Treesitter & LSP semantic tokens
        ["@comment"] = { link = "Comment" },
        ["@none"] = { bg = "NONE", fg = "NONE" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@operator"] = { link = "Operator" },
        ["@punctuation.delimiter"] = { link = "Delimiter" },
        ["@punctuation.bracket"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Delimiter" },
        ["@string"] = { link = "String" },
        ["@string.regex"] = { link = "String" },
        ["@string.regexp"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.special.path"] = { link = "Underlined" },
        ["@string.special.symbol"] = { link = "Identifier" },
        ["@string.special.url"] = { link = "Underlined" },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },
        ["@float"] = { link = "Float" },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Special" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@function.method"] = { link = "Function" },
        ["@method"] = { link = "Function" },
        ["@method.call"] = { link = "Function" },
        ["@constructor"] = { link = "Special" },
        ["@parameter"] = { link = "Identifier" },
        ["@keyword"] = { link = "Keyword" },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.debug"] = { link = "Debug" },
        ["@keyword.directive"] = { link = "PreProc" },
        ["@keyword.directive.define"] = { link = "Define" },
        ["@keyword.exception"] = { link = "Exception" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.import"] = { link = "Include" },
        ["@keyword.operator"] = { link = "GruvlightRed" },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@keyword.storage"] = { link = "StorageClass" },
        ["@conditional"] = { link = "Conditional" },
        ["@repeat"] = { link = "Repeat" },
        ["@debug"] = { link = "Debug" },
        ["@label"] = { link = "Label" },
        ["@include"] = { link = "Include" },
        ["@exception"] = { link = "Exception" },
        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "Type" },
        ["@type.definition"] = { link = "Typedef" },
        ["@type.qualifier"] = { link = "Type" },
        ["@storageclass"] = { link = "StorageClass" },
        ["@attribute"] = { link = "PreProc" },
        ["@field"] = { link = "Identifier" },
        ["@property"] = { link = "Identifier" },
        ["@variable"] = { link = "GruvlightFg1" },
        ["@variable.builtin"] = { link = "Special" },
        ["@variable.member"] = { link = "Identifier" },
        ["@variable.parameter"] = { link = "Identifier" },
        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Special" },
        ["@constant.macro"] = { link = "Define" },

        ["@markup"] = { link = "GruvlightFg1" },
        ["@markup.strong"] = { bold = config.bold },
        ["@markup.italic"] = { link = "@text.emphasis" },
        ["@markup.underline"] = { underline = config.underline },
        ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
        ["@markup.heading"] = { link = "Title" },
        ["@markup.raw"] = { link = "String" },
        ["@markup.math"] = { link = "Special" },
        ["@markup.environment"] = { link = "Macro" },
        ["@markup.environment.name"] = { link = "Type" },
        ["@markup.link"] = { link = "Underlined" },
        ["@markup.link.label"] = { link = "SpecialChar" },
        ["@markup.list"] = { link = "Delimiter" },
        ["@markup.list.checked"] = { link = "GruvlightGreen" },
        ["@markup.list.unchecked"] = { link = "GruvlightGray" },

        ["@comment.todo"] = { link = "Todo" },
        ["@comment.note"] = { link = "SpecialComment" },
        ["@comment.warning"] = { link = "WarningMsg" },
        ["@comment.error"] = { link = "ErrorMsg" },

        ["@diff.plus"] = { link = "diffAdded" },
        ["@diff.minus"] = { link = "diffRemoved" },
        ["@diff.delta"] = { link = "diffChanged" },

        ["@module"] = { link = "GruvlightFg1" },
        ["@namespace"] = { link = "GruvlightFg1" },
        ["@symbol"] = { link = "Identifier" },

        ["@text"] = { link = "GruvlightFg1" },
        ["@text.strong"] = { bold = config.bold },
        ["@text.emphasis"] = { italic = config.italic.emphasis },
        ["@text.underline"] = { underline = config.underline },
        ["@text.strike"] = { strikethrough = config.strikethrough },
        ["@text.title"] = { link = "Title" },
        ["@text.literal"] = { link = "String" },
        ["@text.uri"] = { link = "Underlined" },
        ["@text.math"] = { link = "Special" },
        ["@text.environment"] = { link = "Macro" },
        ["@text.environment.name"] = { link = "Type" },
        ["@text.reference"] = { link = "Constant" },
        ["@text.todo"] = { link = "Todo" },
        ["@text.todo.checked"] = { link = "GruvlightGreen" },
        ["@text.todo.unchecked"] = { link = "GruvlightGray" },
        ["@text.note"] = { link = "SpecialComment" },
        ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
        ["@text.warning"] = { link = "WarningMsg" },
        ["@text.danger"] = { link = "ErrorMsg" },
        ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
        ["@text.diff.add"] = { link = "diffAdded" },
        ["@text.diff.delete"] = { link = "diffRemoved" },

        ["@tag"] = { link = "Tag" },
        ["@tag.attribute"] = { link = "Identifier" },
        ["@tag.delimiter"] = { link = "Delimiter" },

        ["@punctuation"] = { link = "Delimiter" },
        ["@macro"] = { link = "Macro" },
        ["@structure"] = { link = "Structure" },

        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@macro" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@constructor" },
        ["@lsp.type.macro"] = { link = "@macro" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.modifier.java"] = { link = "@keyword.type.java" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.variable"] = { link = "@variable" },
    }

    for group, hl in pairs(config.overrides) do
        if groups[group] then
            groups[group].link = nil -- avoid mixing links with other attrs
        end
        groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
    end

    return groups
end

---@param config GruvlightConfig?
Gruvlight.setup = function(config)
    Gruvlight.config = vim.deepcopy(default_config)
    Gruvlight.config = vim.tbl_deep_extend("force", Gruvlight.config, config or {})
end

--- main load function
Gruvlight.load = function()
    if vim.version().minor < 8 then
        vim.notify_once("gruvlight.nvim: you must use neovim 0.8 or higher")
        return
    end

    -- reset colors
    if vim.g.colors_name then
        vim.cmd.hi("clear")
    end
    vim.g.colors_name = "gruvlight"
    vim.o.termguicolors = true

    local groups = get_groups()

    -- add highlights
    for group, settings in pairs(groups) do
        vim.api.nvim_set_hl(0, group, settings)
    end
end

return Gruvlight
