[font]
size = 11.0

[font.normal]
family = "Iosevka Nerd Font"
# family = "JetBrains Mono"
style=  "Regular"

[font.bold]
family = "Iosevka Nerd Font"
# family = "JetBrains Mono"
style = "bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "bolditalic"

[font.italic]
family = "Iosevka Nerd Font"
style = "italic"

[window.padding]
x = 12
y = 12
