[font]
size = 11.0

[font.normal]
family = "Iosevka Nerd Font"

[font.bold]
family = "Iosevka Nerd Font"
style = "bold"

[font.bold_italic]
family = "Iosevka"
style = "bolditalic"

[font.italic]
family = "Iosevka"
style = "italic"

[window.padding]
x = 12
y = 12
