[font]
size = 11.0
normal = {family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "bold"}
bold_italic = {family = "Iosevka Nerd Font", style = "bold"}
italic = {family = "Iosevka Nerd Font", style = "italic"}

[window]
padding = {x = 12, y = 12}
